// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRU6VEp5sdvNJaxo_Jvy8TZwXDfMgloEw',
    appId: '1:827201542184:web:2fbd3b6a88a2cef47b3d1d',
    messagingSenderId: '827201542184',
    projectId: 'realdatingfinnal',
    authDomain: 'realdatingfinnal.firebaseapp.com',
    storageBucket: 'realdatingfinnal.appspot.com',
    measurementId: 'G-R95CBH9G5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP0Tlmvn-0b2OBgloFDCXu9gTYDN-G_PY',
    appId: '1:827201542184:android:98d5d2a49ab8e98d7b3d1d',
    messagingSenderId: '827201542184',
    projectId: 'realdatingfinnal',
    storageBucket: 'realdatingfinnal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKD8k99wmOwtjGljSGnVtHEzN628T5x70',
    appId: '1:827201542184:ios:f37411cd196f42a17b3d1d',
    messagingSenderId: '827201542184',
    projectId: 'realdatingfinnal',
    storageBucket: 'realdatingfinnal.appspot.com',
    iosBundleId: 'com.example.pushNotificationsFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKD8k99wmOwtjGljSGnVtHEzN628T5x70',
    appId: '1:827201542184:ios:06dc22fb6291b1897b3d1d',
    messagingSenderId: '827201542184',
    projectId: 'realdatingfinnal',
    storageBucket: 'realdatingfinnal.appspot.com',
    iosBundleId: 'com.example.pushNotificationsFirebaseFlutter.RunnerTests',
  );
}
